version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ricardo@0511
      MYSQL_DATABASE: algafood
      MYSQL_USER: algafood-api
      MYSQL_PASSWORD: Ricardo@0511
    ports:
      - "3306:3306"